//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WNpctool.rc
//
#define IDC_BTN_MODE_APPLY              3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WNPCTOOL_DIALOG             102
#define IDR_MAINMENU                    129
#define IDD_DIALOG_MODE                 130
#define IDD_DIALOG_SN                   131
#define IDD_DIALOG_WIFIMAC              132
#define IDB_BMP_GREENLED                132
#define IDD_DIALOG_LANMAC               133
#define IDB_BMP_REDLED                  133
#define IDD_DIALOG_BTMAC                134
#define IDI_ICON1                       134
#define IDR_WNFRAME                     134
#define IDD_DIALOG_IMEI                 135
#define IDC_CB_DEVICES                  1000
#define ID_BTN_WRITE                    1001
#define IDC_STATIC_SN                   1002
#define IDC_STATIC_WIFIMAC              1003
#define IDC_STATIC_LANMAC               1004
#define IDC_STATIC_BTMAC                1005
#define IDC_EDIT_SN                     1006
#define IDC_EDIT_WIFIMAC                1007
#define IDC_EDIT_LANMAC                 1008
#define IDC_EDIT_BTMAC                  1009
#define IDC_LIST2                       1010
#define IDC_LIST_LOG                    1010
#define IDC_STATIC_BTMAC2               1010
#define IDC_STATIC_STATUS               1011
#define IDC_LABEL_DEVICE                1012
#define IDC_TAB_SNMAC                   1013
#define IDC_EDIT_BTMAC2                 1013
#define IDC_EDIT_IMEI                   1013
#define IDC_BTN_MODE_OK                 1014
#define IDC_BTN_MODE_CANCEL             1015
#define IDC_CHECK_SN_SELECT             1016
#define IDC_RADIO_MANUAL_DEVSN          1017
#define IDC_RADIO_AUTO_DEVSN            1018
#define IDC_RADIO_FILE_WIFIMAC          1019
#define IDC_LABEL_SN_PREFIX             1020
#define IDC_EDIT_DEVSN_PREFIX           1021
#define IDC_LABEL_SN_PREFIX2            1022
#define IDC_EDIT_DEVSN_SUFFIX           1023
#define IDC_LABEL_SN_LEN                1024
#define IDC_EDIT_DEVSN_SEGMENT_START    1025
#define IDC_LABEL_SN_SEGMENT_START      1026
#define IDC_LABEL_SN_SEGMENT_CURRENT    1027
#define IDC_EDIT_DEVSN_SEGMENT_CURRENT  1028
#define IDC_LABEL_SN_SEGMENT_END        1029
#define IDC_EDIT_DEVSN_SEGMENT_END      1030
#define IDC_LABEL_SN_SEGMENT_COUNT      1031
#define IDC_EDIT_DEVSN_SEGMENT_COUNT    1032
#define IDC_LABEL_DEVSN_FILE_PATH       1033
#define IDC_EDIT_DEVSN_FILE_PATH        1034
#define IDC_BUTTON_DEVSN_FILE_PATH      1035
#define IDC_CHECK_WIFIMAC_SELECT        1036
#define IDC_EDIT_DEVSN_LEN              1036
#define IDC_RADIO_MANUAL_WIFIMAC        1037
#define IDC_RADIO_AUTO_WIFIMAC          1038
#define IDC_LABEL_WIFIMAC_PREFIX        1039
#define IDC_EDIT_WIFIMAC_PREFIX         1040
#define IDC_LABEL_WIFIMAC_PREFIX2       1041
#define IDC_EDIT_WIFIMAC_SUFFIX         1042
#define IDC_LABEL_WIFIMAC_SEGMENT_START 1043
#define IDC_EDIT_WIFIMAC_SEGMENT_START  1044
#define IDC_LABEL_WIFIMAC_SEGMENT_CURRENT 1045
#define IDC_EDIT_WIFIMAC_SEGMENT_CURRENT 1046
#define IDC_LABEL_WIFIMAC_SEGMENT_END   1047
#define IDC_EDIT_WIFIMAC_SEGMENT_END    1048
#define IDC_LABEL_WIFIMAC_SEGMENT_COUNT 1049
#define IDC_EDIT_WIFIMAC_SEGMENT_COUNT  1050
#define IDC_LABEL_WIFIMAC_FILE_PATH     1051
#define IDC_EDIT_WIFIMAC_FILE_PATH      1052
#define IDC_BUTTON_WIFIMAC_FILE_PATH    1053
#define IDC_CHECK_LANMAC_SELECT         1054
#define IDC_RADIO_MANUAL_LANMAC         1055
#define IDC_RADIO_AUTO_LANMAC           1056
#define IDC_RADIO_FILE_LANMAC           1057
#define IDC_LABEL_LANMAC_PREFIX         1058
#define IDC_EDIT_LANMAC_PREFIX          1059
#define IDC_LABEL_LANMAC_PREFIX2        1060
#define IDC_EDIT_LANMAC_SUFFIX          1061
#define IDC_LABEL_LANMAC_SEGMENT_START  1062
#define IDC_EDIT_LANMAC_SEGMENT_START   1063
#define IDC_LABEL_LANMAC_SEGMENT_CURRENT 1064
#define IDC_EDIT_LANMAC_SEGMENT_CURRENT 1065
#define IDC_LABEL_LANMAC_SEGMENT_END    1066
#define IDC_EDIT_LANMAC_SEGMENT_END     1067
#define IDC_LABEL_LANMAC_SEGMENT_COUNT  1068
#define IDC_EDIT_LANMAC_SEGMENT_COUNT   1069
#define IDC_LABEL_LANMAC_FILE_PATH      1070
#define IDC_EDIT_LANMAC_FILE_PATH       1071
#define IDC_BUTTON_LANMAC_FILE_PATH     1072
#define IDC_CHECK_BTMAC_SELECT          1073
#define IDC_RADIO_MANUAL_BTMAC          1074
#define IDC_RADIO_AUTO_BTMAC            1075
#define IDC_RADIO_FILE_BTMAC            1076
#define IDC_LABEL_BTMAC_PREFIX          1077
#define IDC_EDIT_BTMAC_PREFIX           1078
#define IDC_LABEL_BTMAC_PREFIX2         1079
#define IDC_EDIT_BTMAC_SUFFIX           1080
#define IDC_LABEL_BTMAC_SEGMENT_START   1081
#define IDC_EDIT_BTMAC_SEGMENT_START    1082
#define IDC_LABEL_BTMAC_SEGMENT_CURRENT 1083
#define IDC_EDIT_BTMAC_SEGMENT_CURRENT  1084
#define IDC_LABEL_BTMAC_SEGMENT_END     1085
#define IDC_EDIT_BTMAC_SEGMENT_END      1086
#define IDC_LABEL_BTMAC_SEGMENT_COUNT   1087
#define IDC_EDIT_BTMAC_SEGMENT_COUNT    1088
#define IDC_LABEL_BTMAC_FILE_PATH       1089
#define IDC_EDIT_BTMAC_FILE_PATH        1090
#define IDC_BUTTON_BTMAC_FILE_PATH      1091
#define IDC_RADIO_FILE_SN               1092
#define IDC_PICTURE_DEVICE              1093
#define IDC_LIST_REPORT                 1094
#define IDC_BUTTON_LOADER               1095
#define IDC_EDIT1                       1096
#define IDC_EDIT_LOADER                 1096
#define IDC_CHECK_IMEI_SELECT           1097
#define IDC_STATIC_IMEI                 1098
#define IDC_RADIO_MANUAL_IMEI           1099
#define IDC_RADIO_AUTO_IMEI             1100
#define IDC_RADIO_FILE_IMEI             1101
#define IDC_LABEL_IMEI_SEGMENT_START    1102
#define IDC_EDIT_IMEI_SEGMENT_START     1103
#define IDC_LABEL_IMEI_SEGMENT_CURRENT  1104
#define IDC_EDIT_IMEI_SEGMENT_CURRENT   1105
#define IDC_LABEL_IMEI_SEGMENT_END      1106
#define IDC_EDIT_IMEI_SEGMENT_END       1107
#define IDC_LABEL_IMEI_SEGMENT_COUNT    1108
#define IDC_EDIT_IMEI_SEGMENT_COUNT     1109
#define IDC_LABEL_IMEI_FILE_PATH        1110
#define IDC_EDIT_IMEI_FILE_PATH         1111
#define IDC_BUTTON_IMEI_FILE_PATH       1112
#define IDC_STATIC_SUCCESS              1113
#define IDC_STATIC_FAIL                 1114
#define IDC_STATIC_SUCCESS_COUNT        1115
#define IDC_STATIC_FAIL_COUNT           1116
#define IDC_STATIC_TOTAL_COUNT          1117
#define IDC_STATIC_TOTAL                1118
#define IDC_CHECK_OEM                   1119
#define IDC_OEM                         1120
#define IDC_STATIC_OEM                  1120
#define ID_SETTING                      32771
#define ID_HELP32772                    32772
#define ID_HELP_FOLDER                  32773
#define ID_LOG_FOLDER                   32774
#define ID_SETTING_MODE                 32775
#define ID_SETTING_READ                 32776
#define ID_HELP_LANGUAGE                32777
#define ID_LANGUAGE_CHINESE             32778
#define ID_LANGUAGE_ENGLISH             32779
#define ID_SETTING_AUTO                 32780
#define ID_SETTING_RESET                32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
